### ISSUE TITLE
question about reward 

### ISSUE THREAD

**Issue by unnir** [MichelDeudon/neural-combinatorial-optimization-rl-tensorflow#2]
Hi,

thanks for uploading the code, I just have one question:

I want to use my custom reward, do I need to update the reward only in the dataset.py file?https://github.com/MichelDeudon/neural-combinatorial-optimization-rl-tensorflow/blob/c6442ef3716a54ddaf125a536e31bd1a5f1e91e5/Ptr_Net_TSPTW/dataset.py#L15

or something else too? 

...and I'm working on different problem (not TSP)

**Comment by MichelDeudon** [comment]
Hi,

The reward defined in the dataset.py file is used to perform local search with 2-opt. If you want to customize the reward for the RL setting, you have to update the tensorflow code in the actor.py file (in the environment scope).

**Comment by unnir** [comment]
thank you!
