### ISSUE TITLE
How about the performance?

### ISSUE THREAD

**Issue by Larry0125** [MichelDeudon/neural-combinatorial-optimization-rl-tensorflow#3]
Hi, How does this model mork? Does This model beat existing baselines for TSP?

**Comment by MichelDeudon** [comment]
Hi Larry0125,
Here's references to the spirit of this work:
- https://arxiv.org/pdf/1611.09940.pdf
- https://link.springer.com/chapter/10.1007/978-3-319-93031-2_12

Concorde is a good way to go if you want performance on the TSP.
http://www.math.uwaterloo.ca/tsp/concorde/gui/gui.htm
