### ISSUE TITLE
decoder looking up the next position

### ISSUE THREAD

**Issue by kinsumliu** [MichelDeudon/neural-combinatorial-optimization-rl-tensorflow#5]
hi, the decoder is using this line to retrieve the position:
`new_decoder_input = tf.gather(self.h,position)[0]`

However, since we are doing the lookup on a batch of sequence, we should use `tf.batch_gather` so that we gather independently for each instance in the batch. I believe using `tf.gather` with `[0]` won't achieve what it is intended to do.

**Comment by MichelDeudon** [comment]
@kinsumliu, this has to do with lstm cells and the way you shape your sequence.

**Comment by kinsumliu** [comment]
Your way to gather in the new code https://github.com/MichelDeudon/encode-attend-navigate is fine. But this old repo seems not to work as intended.

I can provide an example that I follow your way to shape the sequence (and for illustration I set the cell state size to be 2). As the input, we have a batch of 3 sequence (maxlength = 4):
```
input = tf.constant([
  [[0,0],[1,1],[2,2],[3,3]],
  [[0,0],[4,4],[5,5],[6,6]],
  [[0,0],[7,7],[8,8],[9,9]],
])
tranposed = tf.transpose(input, [1,0,2]) # same as the h in the code [time steps x batch size x state] 
position = tf.constant([0,1,2])
```

Then we try to gather:
```
new_input = tf.gather(tranposed, position)
print(new_input.shape)
with tf.Session() as sess:
  print(sess.run([new_input]))
```

The result will be:
```
(3, 3, 2)
[array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[1, 1],
        [4, 4],
        [7, 7]],

       [[2, 2],
        [5, 5],
        [8, 8]]], dtype=int32)]
```

However we actually want [0,0] [4,4] [8,8]. Use ` batch_gather`:
```
new_input = tf.batch_gather(input, tf.expand_dims(position,axis=-1))
print(new_input.shape)
with tf.Session() as sess:
  print(sess.run([new_input]))
```
Then we get:
```
(3, 1, 2)
[array([[[0, 0]],

       [[4, 4]],

       [[8, 8]]], dtype=int32)]
```

**Comment by kinsumliu** [comment]
The code in the new repo:
```
idx_ = tf.stack([tf.range(self.batch_size,dtype=tf.int32), idx],1) # idx with batch   
query1 = tf.gather_nd(actor_encoding, idx_)
```
But for the code in the old repo, I think it won't work with the `stack` and `range`

**Comment by MichelDeudon** [comment]
Thanks kinsumliu! :)
