### ISSUE TITLE
Solving TSP with actual distance matrix

### ISSUE THREAD

**Issue by Tariqshah457** [MichelDeudon/neural-combinatorial-optimization-rl-tensorflow#7]
Hello

I hope that you are doing well.
I was trying to use your code to solve a simple TSP problem with only three cities.
![1](https://user-images.githubusercontent.com/56183850/88145007-ff74fc80-cc23-11ea-9109-04048876280c.JPG)
But don't know how to incorporate my data into your algorithm. 
Can you suggest any solution?

Thanks in advance.
Regards

**Comment by MichelDeudon** [comment]
Hi,

If your distance matrix is euclidean (or "almost"), you can estimate coordinates but this is not the case here.
In your case, the distance matrix is not even symmetric. I did something similar in the past, inspired by [ant colony optimization](https://en.wikipedia.org/wiki/Ant_colony_optimization_algorithms) and starting from this repo [MichelDeudon/encode-attend-navigate](https://github.com/MichelDeudon/encode-attend-navigate).

Regards.
